name: student_project

channels:
- conda
- r

dependencies:
- numpy
- pandas 
- jupyterlab
- matplotlib
- scipy
- statsmodels
- r-essentials
- r-DiagrammeR
- r-AER
- r-ggplot2
- r-tidyverse
- r-digest
- pip:
  - grmpy
